### ISSUE TITLE
Don't use this.setState() in componentWillUpdate()

### ISSUE THREAD

**Issue by robvenn** [DevelopmentArc/react-indepth#3]
According to the chapter "Tapping into componentWillUpdate()" it's safe to call setState() without triggering another update.

However, after looking it up in the docs and testing it for myself it looks like this is wrong, see the note on https://facebook.github.io/react/docs/component-specs.html#updating-componentwillupdate : "You cannot use this.setState() in this method. If you need to update state in response to a prop change, use componentWillReceiveProps instead."

**Comment by jamespolanco** [comment]
Hi Robin,
Thanks for pointing this out. This was something that was not clear in the docs originally (I really don't recall seeing that warning last time I read that page) and in the past it _seemed_ ok, but it is risky due to how the dirty/render process is managed. I talked to the Reactiflux internals peeps and got a better explanation on why this is bad. The issue is that `setState()` triggers `componentWillUpdate()` with no check, so unless a flag is used on the `setState()` this will cause an infinite loop.

I will be updating this ASAP and I was passed a good chart that shows this in more detail. Thanks again for calling this out to my attention!

**Comment by robvenn** [comment]
Hello James,
You're welcome, this just happened to catch my attention. It's probably one of the lesser used lifecycle methods. Thanks for providing this free book, definitely worth a read and I've learned a few things. Looking forward to see the updated information!

**Comment by jamespolanco** [comment]
All updated in #4, thanks again!
